/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@jonmatum/react-mfe-shell/dist/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // Design token colors that match the MFE library
      colors: {
        // Semantic colors
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        danger: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        // Add 'error' as alias for 'danger' since MFE library uses both
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        // Theme-aware semantic colors
        'text-primary': '#1f2937',
        'text-secondary': '#6b7280',
        'text-tertiary': '#9ca3af',
        'text-inverse': '#ffffff',
        'text-disabled': '#d1d5db',
        'background-primary': '#ffffff',
        'background-secondary': '#f9fafb',
        'surface-primary': '#ffffff',
        'surface-secondary': '#f3f4f6',
        'border-primary': '#e5e7eb',
        'border-secondary': '#d1d5db',
        'border-tertiary': '#9ca3af',
        'border-focus': '#3b82f6',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  // Comprehensive safelist to ensure ALL MFE component classes are generated
  safelist: [
    // Base interactive classes
    'inline-flex',
    'items-center',
    'justify-center',
    'transition-colors',
    'duration-200',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    
    // Text colors - semantic
    'text-primary',
    'text-secondary', 
    'text-tertiary',
    'text-inverse',
    'text-disabled',
    'text-white',
    'text-text-primary',
    'text-text-secondary',
    
    // Text colors - all variants for dynamic generation
    'text-primary-300',
    'text-primary-400',
    'text-primary-500',
    'text-primary-600',
    'text-primary-700',
    'text-primary-800',
    'text-primary-900',
    'text-success-300',
    'text-success-400',
    'text-success-500',
    'text-success-600',
    'text-success-700',
    'text-success-800',
    'text-success-900',
    'text-warning-300',
    'text-warning-400',
    'text-warning-500',
    'text-warning-600',
    'text-warning-700',
    'text-warning-800',
    'text-warning-900',
    'text-danger-300',
    'text-danger-400',
    'text-danger-500',
    'text-danger-600',
    'text-danger-700',
    'text-danger-800',
    'text-danger-900',
    'text-error-300',
    'text-error-400',
    'text-error-500',
    'text-error-600',
    'text-error-700',
    'text-error-800',
    'text-error-900',
    
    // Background colors - all variants for dynamic generation
    'bg-primary-50',
    'bg-primary-100',
    'bg-primary-200',
    'bg-primary-300',
    'bg-primary-400',
    'bg-primary-500',
    'bg-primary-600',
    'bg-primary-700',
    'bg-primary-800',
    'bg-primary-900',
    'bg-success-50',
    'bg-success-100',
    'bg-success-200',
    'bg-success-300',
    'bg-success-400',
    'bg-success-500',
    'bg-success-600',
    'bg-success-700',
    'bg-success-800',
    'bg-success-900',
    'bg-warning-50',
    'bg-warning-100',
    'bg-warning-200',
    'bg-warning-300',
    'bg-warning-400',
    'bg-warning-500',
    'bg-warning-600',
    'bg-warning-700',
    'bg-warning-800',
    'bg-warning-900',
    'bg-danger-50',
    'bg-danger-100',
    'bg-danger-200',
    'bg-danger-300',
    'bg-danger-400',
    'bg-danger-500',
    'bg-danger-600',
    'bg-danger-700',
    'bg-danger-800',
    'bg-danger-900',
    'bg-error-50',
    'bg-error-100',
    'bg-error-200',
    'bg-error-300',
    'bg-error-400',
    'bg-error-500',
    'bg-error-600',
    'bg-error-700',
    'bg-error-800',
    'bg-error-900',
    
    // Semantic background colors
    'bg-background-primary',
    'bg-background-secondary',
    'bg-surface-primary',
    'bg-surface-secondary',
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-600',
    'bg-gray-700',
    'bg-gray-800',
    'bg-gray-900',
    
    // Border colors - all variants for dynamic generation
    'border-primary-200',
    'border-primary-300',
    'border-primary-400',
    'border-primary-500',
    'border-primary-600',
    'border-primary-700',
    'border-success-200',
    'border-success-300',
    'border-success-400',
    'border-success-500',
    'border-success-600',
    'border-success-700',
    'border-warning-200',
    'border-warning-300',
    'border-warning-400',
    'border-warning-500',
    'border-warning-600',
    'border-warning-700',
    'border-danger-200',
    'border-danger-300',
    'border-danger-400',
    'border-danger-500',
    'border-danger-600',
    'border-danger-700',
    'border-error-200',
    'border-error-300',
    'border-error-400',
    'border-error-500',
    'border-error-600',
    'border-error-700',
    
    // Semantic border colors
    'border-border-primary',
    'border-border-secondary',
    'border-border-tertiary',
    'border-border-focus',
    'border-gray-200',
    'border-gray-300',
    'border',
    'border-2',
    
    // Hover states - all variants
    'hover:bg-primary-50',
    'hover:bg-primary-600',
    'hover:bg-primary-700',
    'hover:bg-success-50',
    'hover:bg-success-600',
    'hover:bg-success-700',
    'hover:bg-warning-50',
    'hover:bg-warning-600',
    'hover:bg-warning-700',
    'hover:bg-danger-50',
    'hover:bg-danger-600',
    'hover:bg-danger-700',
    'hover:bg-error-50',
    'hover:bg-error-600',
    'hover:bg-error-700',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    
    // Focus states - all variants
    'focus:ring-primary-400',
    'focus:ring-primary-500',
    'focus:ring-success-400',
    'focus:ring-success-500',
    'focus:ring-warning-400',
    'focus:ring-warning-500',
    'focus:ring-danger-400',
    'focus:ring-danger-500',
    'focus:ring-error-400',
    'focus:ring-error-500',
    'focus:border-primary-500',
    'focus:border-success-500',
    'focus:border-warning-500',
    'focus:border-danger-500',
    'focus:border-error-500',
    
    // Dark mode variants - all combinations
    'dark:bg-primary-500',
    'dark:bg-primary-600',
    'dark:bg-primary-900',
    'dark:bg-success-500',
    'dark:bg-success-600',
    'dark:bg-success-900',
    'dark:bg-warning-500',
    'dark:bg-warning-600',
    'dark:bg-warning-900',
    'dark:bg-danger-500',
    'dark:bg-danger-600',
    'dark:bg-danger-900',
    'dark:bg-error-500',
    'dark:bg-error-600',
    'dark:bg-error-900',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:text-primary-300',
    'dark:text-success-300',
    'dark:text-warning-300',
    'dark:text-danger-300',
    'dark:text-error-300',
    'dark:text-white',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:border-primary-600',
    'dark:border-primary-700',
    'dark:border-success-600',
    'dark:border-success-700',
    'dark:border-warning-600',
    'dark:border-warning-700',
    'dark:border-danger-600',
    'dark:border-danger-700',
    'dark:border-error-600',
    'dark:border-error-700',
    'dark:border-gray-600',
    'dark:border-gray-700',
    'dark:hover:bg-primary-600',
    'dark:hover:bg-success-600',
    'dark:hover:bg-warning-600',
    'dark:hover:bg-danger-600',
    'dark:hover:bg-error-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-600',
    'dark:focus:ring-primary-400',
    'dark:focus:ring-success-400',
    'dark:focus:ring-warning-400',
    'dark:focus:ring-danger-400',
    'dark:focus:ring-error-400',
    
    // Special dark mode background patterns
    'dark:bg-primary-900/30',
    'dark:bg-success-900/30',
    'dark:bg-warning-900/30',
    'dark:bg-danger-900/30',
    'dark:bg-error-900/30',
    'dark:hover:bg-primary-900/20',
    'dark:hover:bg-success-900/20',
    'dark:hover:bg-warning-900/20',
    'dark:hover:bg-danger-900/20',
    'dark:hover:bg-error-900/20',
    'dark:border-primary-700/50',
    'dark:border-success-700/50',
    'dark:border-warning-700/50',
    'dark:border-danger-700/50',
    'dark:border-error-700/50',
    
    // Button sizes and padding
    'px-2',
    'px-2.5',
    'px-3',
    'px-4',
    'px-6',
    'px-8',
    'py-1',
    'py-1.5',
    'py-2',
    'py-2.5',
    'py-3',
    'py-4',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    
    // General spacing
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'm-1',
    'm-2',
    'm-3',
    'm-4',
    'mt-1',
    'mt-2',
    'mt-4',
    'mb-1',
    'mb-2',
    'mb-4',
    'ml-1',
    'ml-2',
    'mr-2',
    
    // Flexbox and layout
    'flex',
    'inline-flex',
    'items-center',
    'justify-center',
    'justify-between',
    'space-x-1',
    'space-x-1.5',
    'space-x-2',
    'space-x-2.5',
    'space-x-3',
    'space-y-1',
    'space-y-2',
    'space-y-3',
    'gap-1',
    'gap-1.5',
    'gap-2',
    'gap-2.5',
    'gap-3',
    
    // Border radius
    'rounded',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
    
    // Shadows
    'shadow',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    
    // Transitions
    'transition',
    'transition-colors',
    'transition-all',
    'duration-150',
    'duration-200',
    'duration-300',
    
    // Opacity and states
    'opacity-50',
    'opacity-75',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    
    // Positioning
    'relative',
    'absolute',
    'fixed',
    'inset-0',
    'z-10',
    'z-20',
    'z-30',
    'z-40',
    'z-50',
    
    // Width and height
    'w-4',
    'w-5',
    'w-6',
    'w-8',
    'w-10',
    'w-12',
    'w-16',
    'w-full',
    'h-4',
    'h-5',
    'h-6',
    'h-8',
    'h-10',
    'h-12',
    'h-16',
    'h-full',
    'min-h-screen',
    
    // Animation
    'animate-spin',
    'animate-pulse',
    
    // Transform
    'transform',
    'translate-x-0',
    'translate-x-4',
    'translate-x-5',
    'translate-x-6',
    
    // Display
    'block',
    'inline-block',
    'hidden',
    'sr-only',
    
    // Font weight
    'font-medium',
    'font-semibold',
    'font-bold',
    
    // Additional utility classes
    'cursor-pointer',
    'cursor-not-allowed',
    'select-none',
    'pointer-events-none',
    'ring-0',
  ],
  plugins: [],
}
