/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@jonmatum/react-mfe-shell/dist/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    // Override default Tailwind tokens with our design system
    extend: {
      // Colors from design tokens
      colors: {
        // Base colors - matching MFE package design tokens
        white: '#ffffff',
        black: '#000000',
        transparent: 'transparent',
        current: 'currentColor',
        
        // Gray scale
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        
        // Semantic colors - matching MFE package
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        danger: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        info: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        
        // Theme-aware colors (CSS custom properties)
        background: {
          primary: 'var(--color-background-primary)',
          secondary: 'var(--color-background-secondary)',
          tertiary: 'var(--color-background-tertiary)',
        },
        surface: {
          primary: 'var(--color-surface-primary)',
          secondary: 'var(--color-surface-secondary)',
          tertiary: 'var(--color-surface-tertiary)',
          elevated: 'var(--color-surface-elevated)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          inverse: 'var(--color-text-inverse)',
          disabled: 'var(--color-text-disabled)',
        },
        border: {
          primary: 'var(--color-border-primary)',
          secondary: 'var(--color-border-secondary)',
          tertiary: 'var(--color-border-tertiary)',
          focus: 'var(--color-border-focus)',
        },
      },
      
      // Typography from design tokens
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      
      // Spacing from design tokens
      spacing: {
        '0': '0px',
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',
      },
      
      // Shadows from design tokens
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
        inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
        none: 'none',
      },
      
      // Border radius from design tokens
      borderRadius: {
        none: '0px',
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      
      // Animation from design tokens
      transitionDuration: {
        75: '75ms',
        100: '100ms',
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
        700: '700ms',
        1000: '1000ms',
      },
      
      // Z-index from design tokens
      zIndex: {
        0: '0',
        10: '10',
        20: '20',
        30: '30',
        40: '40',
        50: '50',
        auto: 'auto',
      },
    },
  },
  safelist: [
    // Exact classes used by MFE components (from analysis)
    'bg-danger-600',
    'bg-error-100',
    'bg-error-800',
    'bg-gray-800',
    'bg-opacity-50',
    'bg-primary-100',
    'bg-primary-600',
    'bg-primary-800',
    'bg-success-100',
    'bg-success-600',
    'bg-success-800',
    'bg-surface-disabled',
    'bg-surface-elevated',
    'bg-surface-primary',
    'bg-surface-secondary',
    'bg-surface-tertiary',
    'bg-warning-100',
    'bg-warning-600',
    'bg-warning-800',
    
    // Additional background classes used in TaskMaster Pro
    'bg-background-primary',
    'bg-danger-100',
    
    // Text color classes used in TaskMaster Pro
    'text-danger-600',
    'text-primary-600',
    'text-success-600',
    'text-warning-600',
    'text-text-primary',
    'text-text-secondary',
    'text-white',
    
    // Layout and sizing classes used in application
    'w-6',
    'h-6',
    'w-8',
    'h-8',
    'w-12',
    'h-12',
    'w-16',
    'h-16',
    'w-5',
    'h-5',
    
    // Grid and flex classes
    'grid-cols-1',
    'grid-cols-2',
    'md:grid-cols-4',
    'lg:grid-cols-4',
    'flex-col',
    'flex-wrap',
    'items-start',
    'justify-end',
    
    // Spacing classes used in application
    'space-x-2',
    'space-x-3',
    'space-x-4',
    'space-y-4',
    'space-y-6',
    'gap-2',
    'gap-4',
    'gap-6',
    'mb-2',
    'mb-3',
    'mb-4',
    'mb-6',
    'mb-8',
    'mt-4',
    'ml-4',
    'my-4',
    'my-6',
    'p-12',
    'px-3',
    'py-2',
    'py-8',
    
    // Typography classes
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    
    // Border and radius classes
    'border-b',
    'border-border-primary',
    'rounded-lg',
    'rounded-md',
    
    // Responsive classes
    'sm:flex-row',
    'sm:px-6',
    'lg:px-8',
    'max-w-7xl',
    
    // Interactive classes
    'hover:shadow-md',
    'transition-shadow',
    'capitalize',
    
    // Footer specific classes
    'mt-16',
    'border-t',
    'md:flex-row',
    'md:space-y-0',
    'space-y-4',
    'bg-surface-secondary',
    'hover:bg-surface-tertiary',
    'border-border-secondary',
    'text-text-primary',
    'text-xs',
    'text-text-tertiary',
    'hover:text-text-primary',
    'duration-200',
    'space-x-6',
    'space-x-1',
    'py-0.5',
    'w-3',
    'h-3',
    'inline-flex',
    
    // Text classes used by MFE components
    'text-danger-700',
    'text-error-700',
    'text-primary-700',
    'text-success-700',
    'text-warning-700',
    'text-white',
    'text-text-primary',
    'text-text-secondary',
    'text-text-tertiary',
    'text-text-inverse',
    'text-text-disabled',
    
    // Border classes used by MFE components
    'border-danger-200',
    'border-error-200',
    'border-primary-200',
    'border-success-200',
    'border-warning-200',
    'border-border-primary',
    'border-border-secondary',
    'border-border-tertiary',
    'border-border-focus',
    
    // Hover states for buttons
    'hover:bg-danger-700',
    'hover:bg-primary-700',
    'hover:bg-success-700',
    'hover:bg-warning-700',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'hover:bg-gray-700',
    'hover:bg-gray-800',
    
    // Focus states
    'focus:ring-danger-500',
    'focus:ring-primary-500',
    'focus:ring-success-500',
    'focus:ring-warning-500',
    'focus:border-danger-500',
    'focus:border-primary-500',
    'focus:border-success-500',
    'focus:border-warning-500',
    
    // Dark mode variants
    'dark:bg-danger-500',
    'dark:bg-primary-500',
    'dark:bg-success-500',
    'dark:bg-warning-500',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:text-white',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-danger-300',
    'dark:text-primary-300',
    'dark:text-success-300',
    'dark:text-warning-300',
    'dark:border-danger-600',
    'dark:border-primary-600',
    'dark:border-success-600',
    'dark:border-warning-600',
    'dark:border-gray-600',
    'dark:border-gray-700',
    'dark:hover:bg-danger-600',
    'dark:hover:bg-primary-600',
    'dark:hover:bg-success-600',
    'dark:hover:bg-warning-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-600',
    'dark:focus:ring-danger-400',
    'dark:focus:ring-primary-400',
    'dark:focus:ring-success-400',
    'dark:focus:ring-warning-400',
    
    // Badge specific classes with opacity
    'bg-danger-50',
    'bg-primary-50',
    'bg-success-50',
    'bg-warning-50',
    'dark:bg-danger-900/30',
    'dark:bg-primary-900/30',
    'dark:bg-success-900/30',
    'dark:bg-warning-900/30',
    'dark:border-danger-700/50',
    'dark:border-primary-700/50',
    'dark:border-success-700/50',
    'dark:border-warning-700/50',
    
    // Switch component classes
    'h-5',
    'w-9',
    'h-6',
    'w-11',
    'h-8',
    'w-14',
    'h-4',
    'h-7',
    'translate-x-4',
    'translate-x-5',
    'translate-x-6',
    
    // LoadingSpinner component classes
    'h-3',
    'w-3',
    'h-4',
    'w-4',
    'h-8',
    'w-8',
    'h-12',
    'w-12',
    'h-16',
    'w-16',
    'border-2',
    'border-4',
    'border-gray-300',
    'border-t-primary-600',
    'border-t-success-600',
    'border-t-warning-600',
    'border-t-danger-600',
    'border-white/30',
    'border-t-white',
    'border-current/30',
    'border-t-current',
    'animate-spin',
    
    // Typography classes
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    
    // Layout and positioning
    'inline-flex',
    'items-center',
    'justify-center',
    'justify-between',
    'justify-end',
    'space-x-1',
    'space-x-2',
    'space-x-3',
    'space-x-4',
    'space-y-1',
    'space-y-2',
    'space-y-3',
    'space-y-4',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    
    // Padding and margin
    'px-2',
    'px-2.5',
    'px-3',
    'px-4',
    'px-6',
    'px-8',
    'py-1',
    'py-1.5',
    'py-2',
    'py-2.5',
    'py-3',
    'py-4',
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-6',
    'p-8',
    'm-1',
    'm-2',
    'm-3',
    'm-4',
    'mt-1',
    'mt-2',
    'mt-4',
    'mb-1',
    'mb-2',
    'mb-4',
    'ml-1',
    'ml-2',
    'mr-2',
    
    // Border radius
    'rounded',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    
    // Border styles
    'border',
    'border-2',
    
    // Shadows
    'shadow',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    
    // Display and positioning
    'relative',
    'absolute',
    'fixed',
    'block',
    'hidden',
    'flex',
    'grid',
    'inline-block',
    
    // Transitions and animations
    'transition',
    'transition-colors',
    'transition-all',
    'duration-150',
    'duration-200',
    'duration-300',
    'ease-in-out',
    'transform',
    'animate-pulse',
    
    // States
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'hover:opacity-75',
    'active:scale-95',
    
    // Cursor
    'cursor-pointer',
    'cursor-not-allowed',
    
    // Overflow and scrolling
    'overflow-hidden',
    'overflow-auto',
    'scroll-smooth',
    
    // Z-index
    'z-10',
    'z-20',
    'z-30',
    'z-40',
    'z-50',
    
    // Width and height
    'w-full',
    'h-full',
    'min-h-screen',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
  ],
  plugins: [],
};
