// Tailwind CSS Safelist - MINIMAL Level
// Generated on: 2025-08-26T02:02:32.584Z
// Total classes: 105
// Level: Only classes found in source code + essential MFE Shell classes

export const tailwindSafelist = [
  'active:scale-95',
  'bg-background-primary',
  'bg-danger-100',
  'bg-primary-100',
  'bg-success-100',
  'bg-surface-primary',
  'bg-surface-secondary',
  'bg-warning-100',
  'border',
  'border-b',
  'border-border-primary',
  'border-t',
  'btn-enhanced',
  'capitalize',
  'cursor-pointer',
  'disabled:cursor-not-allowed',
  'disabled:opacity-50',
  'duration-200',
  'ease-in-out',
  'flex',
  'flex-1',
  'flex-col',
  'flex-wrap',
  'focus:outline-none',
  'focus:ring-2',
  'focus:ring-primary-500',
  'font-bold',
  'font-medium',
  'font-semibold',
  'gap-2',
  'gap-4',
  'gap-6',
  'grid',
  'grid-cols-1',
  'grid-cols-2',
  'h-12',
  'h-16',
  'h-4',
  'h-5',
  'h-6',
  'h-8',
  'hover:bg-surface-secondary',
  'hover:shadow-lg',
  'items-center',
  'items-start',
  'justify-between',
  'justify-center',
  'lg:px-8',
  'max-w-2xl',
  'max-w-7xl',
  'mb-2',
  'mb-3',
  'mb-4',
  'mb-6',
  'mb-8',
  'md:grid-cols-2',
  'md:grid-cols-4',
  'min-h-screen',
  'ml-4',
  'mt-1',
  'mt-16',
  'mt-4',
  'mx-auto',
  'my-4',
  'p-12',
  'p-3',
  'p-4',
  'p-6',
  'pt-4',
  'px-3',
  'px-4',
  'py-2',
  'py-8',
  'rounded-lg',
  'rounded-md',
  'sm:flex-row',
  'sm:px-6',
  'space-x-2',
  'space-x-3',
  'space-x-4',
  'space-y-4',
  'space-y-6',
  'task-card',
  'text-2xl',
  'text-3xl',
  'text-center',
  'text-danger-600',
  'text-lg',
  'text-primary-600',
  'text-sm',
  'text-success-600',
  'text-text-primary',
  'text-text-secondary',
  'text-text-tertiary',
  'text-warning-600',
  'text-xl',
  'text-xs',
  'transition-all',
  'truncate',
  'w-12',
  'w-4',
  'w-5',
  'w-6',
  'w-8',
  'w-full',
];

// Usage in tailwind.config.js:
// import { tailwindSafelist } from './scripts/safelist-minimal.js';
// 
// export default {
//   // ... other config
//   safelist: tailwindSafelist,
// };
