name: CI (Yarn Alternative)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-yarn:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies with Yarn
        run: |
          # Use yarn which handles optional dependencies better
          yarn install --frozen-lockfile || yarn install

      - name: Run linter
        run: yarn lint

      - name: Run type check
        run: yarn type-check

      - name: Build application
        run: yarn build

      - name: Upload build artifacts
        if: matrix.node-version == 22
        uses: actions/upload-artifact@v4
        with:
          name: dist-yarn
          path: dist/
          retention-days: 7
