name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Aggressive Rollup dependency fix
        run: |
          # Complete clean slate
          rm -rf node_modules package-lock.json
          
          # Install with specific npm configuration
          npm config set fund false
          npm config set audit false
          
          # Install dependencies with specific flags
          npm install --no-optional --no-package-lock
          
          # Explicitly install Rollup native binaries
          npm install @rollup/rollup-linux-x64-gnu --save-optional --no-package-lock
          
          # Verify installation
          ls -la node_modules/@rollup/ || echo "Rollup native binaries directory not found"
          
          # Force rebuild rollup
          npm rebuild rollup --no-package-lock

      - name: Verify Rollup functionality
        run: |
          # Test that rollup can be imported
          node -e "
            try {
              const rollup = require('rollup');
              console.log('✅ Rollup loaded successfully');
            } catch (error) {
              console.error('❌ Rollup failed to load:', error.message);
              process.exit(1);
            }
          "

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        if: matrix.node-version == 22
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
